apiVersion: v1
kind: ReplicationController
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  replicas: 1
  selector:
    name: ubuntu
  template:
    metadata:
      labels:
        name: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
