apiVersion: v1
kind: Service
metadata:
  name: pingsvc
  labels:
    name: pingsvc
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  selector:
    name: pingpodlabel
