apiVersion: v1
kind: ReplicationController
metadata:
  name: rcpodalone
  labels:
    name: rcpodalone
spec:
  replicas: 1
  selector:
    name: dapodalone
  template:
    metadata:
      labels:
        name: dapodalone
    spec:
      containers:
      - name: mypodalone
        image: ipedrazas/podalone
        ports:
        - containerPort: 8080
        env:
          - name: REDIS_HOST
            value: "redis"
